name: Docker Image CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        docker build . --file Dockerfile --tag anandanmb01/docker_test:$TIMESTAMP
        docker tag anandanmb01/docker_test:$TIMESTAMP anandanmb01/docker_test:latest
    - name: Docker Push
      run: |
        docker push anandanmb01/docker_test:latest
        docker push anandanmb01/docker_test:$(date +%Y%m%d%H%M%S)
