name: Docker Image CI

# on:
#   push:
#     branches: [ master ]

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'version_no'
        default: 'latest'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Set TIMESTAMP
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d %H:%M:%S')"
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag anandanmb01/docker_test:"${{ steps.timestamp.outputs.timestamp }}"
        docker tag anandanmb01/docker_test:"${{ steps.timestamp.outputs.timestamp }}" anandanmb01/docker_test:latest
    - name: Docker Push
      run: |
        docker push anandanmb01/docker_test:latest
        docker push anandanmb01/docker_test:"${{ steps.timestamp.outputs.timestamp }}"



# --------------------------------------------------------------------------------------------------------------------------



# jobs:
#   greet:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Send greeting
#       run: echo "Hello ${{ github.event.inputs.name }}"
